language: android 

android:
  components:
    - platform-tools  
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x ./build.sh


script:
    - ./build.sh

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true # to upload artifacts created during the build
  dry-run: false
  on:
    branch: master