version: 0.0.1-build{build}
image: Visual Studio 2017
environment:
  ANDROID_HOME: "C:\\android-sdk-windows"
init:
  - mkdir ANDROID_HOME
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-3859397.zip
  - 7z e sdk-tools-windows-3859397.zip -oANDROID_HOME  
install:
  - yes | "%ANDROID_HOME%\tools\bin\sdkmanager.bat" "platform-tools" "platforms;android-27" "build-tools;27.0.3" "extras;android;m2repository" "extras;google;m2repository"
build_script:
- ps: >-
    nuget restore "Windows\\Shiba.sln"

    msbuild "Windows\\Shiba.sln" /m /verbosity:minimal /p:Configuration=Release

    nuget pack "Windows\\Shiba.nuspec" -Version $env:appveyor_build_version

    Android\gradlew.bat clean assembleRelease --parallel --stacktrace
artifacts:
- path: '**\*.nupkg'
