version: 0.0.1-build{build}
image: Visual Studio 2017
build_script:
- ps: >-
    nuget restore "Windows\\Shiba.sln"
    msbuild "Windows\\Shiba.sln" /m /verbosity:minimal /p:Configuration=Release
    nuget pack "Windows\\Shiba.nuspec" -Version $env:appveyor_build_version
artifacts:
- path: '*.nupkg'
  name: nuget

