version: 0.1.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    nuget restore "UWP\\Shiba.sln"

    msbuild "UWP\\Shiba.sln" /m /verbosity:minimal /p:Configuration=Release

    nuget pack "UWP\\Shiba.nuspec" -Version $env:appveyor_build_version
    
artifacts:
- path: '*.nupkg'
  name: nuget
deploy:
- provider: Environment
  name: nuget
  on:
    branch: master

