//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Shiba.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Shiba.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ShibaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IShibaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot([NotNull] ShibaParser.RootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot([NotNull] ShibaParser.RootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.namespaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaces([NotNull] ShibaParser.NamespacesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.namespaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaces([NotNull] ShibaParser.NamespacesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObj([NotNull] ShibaParser.ObjContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObj([NotNull] ShibaParser.ObjContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] ShibaParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] ShibaParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ShibaParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ShibaParser.ValueContext context);
}
} // namespace Shiba.Parser
