//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Shiba.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Shiba.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ShibaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, NAMESPACE=6, STRING=7, BOOLEAN=8, 
		TOKEN=9, NUMBER=10, Hws=11, Vws=12, DocComment=13, BlockComment=14, LineComment=15, 
		LineCommentExt=16;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "NAMESPACE", "STRING", "BOOLEAN", 
		"TOKEN", "NUMBER", "INT", "EXP", "Hws", "Vws", "DocComment", "BlockComment", 
		"LineComment", "LineCommentExt"
	};


	public ShibaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ShibaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'{'", "','", "'}'", "':'", "'null'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, "NAMESPACE", "STRING", "BOOLEAN", 
		"TOKEN", "NUMBER", "Hws", "Vws", "DocComment", "BlockComment", "LineComment", 
		"LineCommentExt"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Shiba.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ShibaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x12', '\xCF', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\a', '\a', '\x39', '\n', '\a', '\f', '\a', 
		'\xE', '\a', '<', '\v', '\a', '\x3', '\b', '\x3', '\b', '\a', '\b', '@', 
		'\n', '\b', '\f', '\b', '\xE', '\b', '\x43', '\v', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', 
		'P', '\n', '\t', '\x3', '\n', '\x6', '\n', 'S', '\n', '\n', '\r', '\n', 
		'\xE', '\n', 'T', '\x3', '\n', '\a', '\n', 'X', '\n', '\n', '\f', '\n', 
		'\xE', '\n', '[', '\v', '\n', '\x3', '\v', '\x5', '\v', '^', '\n', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x6', '\v', '\x63', '\n', '\v', 
		'\r', '\v', '\xE', '\v', '\x64', '\x5', '\v', 'g', '\n', '\v', '\x3', 
		'\v', '\x5', '\v', 'j', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\a', '\f', 'o', '\n', '\f', '\f', '\f', '\xE', '\f', 'r', '\v', '\f', 
		'\x5', '\f', 't', '\n', '\f', '\x3', '\r', '\x3', '\r', '\x5', '\r', 'x', 
		'\n', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\a', '\x10', '\x89', '\n', '\x10', '\f', '\x10', '\xE', '\x10', 
		'\x8C', '\v', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', 
		'\x10', '\x91', '\n', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', '\x99', '\n', 
		'\x11', '\f', '\x11', '\xE', '\x11', '\x9C', '\v', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\xA1', '\n', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\a', '\x12', '\xA9', '\n', '\x12', '\f', '\x12', '\xE', '\x12', 
		'\xAC', '\v', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\xB4', '\n', '\x13', 
		'\f', '\x13', '\xE', '\x13', '\xB7', '\v', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\a', '\x13', '\xBB', '\n', '\x13', '\f', '\x13', '\xE', '\x13', 
		'\xBE', '\v', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\a', '\x13', '\xC4', '\n', '\x13', '\f', '\x13', '\xE', '\x13', 
		'\xC7', '\v', '\x13', '\a', '\x13', '\xC9', '\n', '\x13', '\f', '\x13', 
		'\xE', '\x13', '\xCC', '\v', '\x13', '\x3', '\x13', '\x3', '\x13', '\x4', 
		'\x8A', '\x9A', '\x2', '\x14', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\x2', '\x19', '\x2', '\x1B', '\r', '\x1D', 
		'\xE', '\x1F', '\xF', '!', '\x10', '#', '\x11', '%', '\x12', '\x3', '\x2', 
		'\r', '\x3', '\x2', '$', '$', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x3', '\x2', '\x32', ';', '\x3', '\x2', '\x33', ';', '\x4', 
		'\x2', 'G', 'G', 'g', 'g', '\x4', '\x2', '-', '-', '/', '/', '\x4', '\x2', 
		'\v', '\v', '\"', '\"', '\x4', '\x2', '\f', '\f', '\xE', '\xF', '\x4', 
		'\x2', '\f', '\f', '\xF', '\xF', '\x3', '\x2', '\f', '\f', '\x2', '\xE1', 
		'\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\'', '\x3', '\x2', '\x2', '\x2', '\x5', ')', '\x3', 
		'\x2', '\x2', '\x2', '\a', '+', '\x3', '\x2', '\x2', '\x2', '\t', '-', 
		'\x3', '\x2', '\x2', '\x2', '\v', '/', '\x3', '\x2', '\x2', '\x2', '\r', 
		'\x34', '\x3', '\x2', '\x2', '\x2', '\xF', '=', '\x3', '\x2', '\x2', '\x2', 
		'\x11', 'O', '\x3', '\x2', '\x2', '\x2', '\x13', 'R', '\x3', '\x2', '\x2', 
		'\x2', '\x15', ']', '\x3', '\x2', '\x2', '\x2', '\x17', 's', '\x3', '\x2', 
		'\x2', '\x2', '\x19', 'u', '\x3', '\x2', '\x2', '\x2', '\x1B', '{', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'\x83', '\x3', '\x2', '\x2', '\x2', '!', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '#', '\xA4', '\x3', '\x2', '\x2', '\x2', '%', '\xAF', '\x3', '\x2', 
		'\x2', '\x2', '\'', '(', '\a', '}', '\x2', '\x2', '(', '\x4', '\x3', '\x2', 
		'\x2', '\x2', ')', '*', '\a', '.', '\x2', '\x2', '*', '\x6', '\x3', '\x2', 
		'\x2', '\x2', '+', ',', '\a', '\x7F', '\x2', '\x2', ',', '\b', '\x3', 
		'\x2', '\x2', '\x2', '-', '.', '\a', '<', '\x2', '\x2', '.', '\n', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x30', '\a', 'p', '\x2', '\x2', '\x30', '\x31', 
		'\a', 'w', '\x2', '\x2', '\x31', '\x32', '\a', 'n', '\x2', '\x2', '\x32', 
		'\x33', '\a', 'n', '\x2', '\x2', '\x33', '\f', '\x3', '\x2', '\x2', '\x2', 
		'\x34', '\x35', '\a', '\x42', '\x2', '\x2', '\x35', ':', '\x5', '\x13', 
		'\n', '\x2', '\x36', '\x37', '\a', '\x30', '\x2', '\x2', '\x37', '\x39', 
		'\x5', '\x13', '\n', '\x2', '\x38', '\x36', '\x3', '\x2', '\x2', '\x2', 
		'\x39', '<', '\x3', '\x2', '\x2', '\x2', ':', '\x38', '\x3', '\x2', '\x2', 
		'\x2', ':', ';', '\x3', '\x2', '\x2', '\x2', ';', '\xE', '\x3', '\x2', 
		'\x2', '\x2', '<', ':', '\x3', '\x2', '\x2', '\x2', '=', '\x41', '\a', 
		'$', '\x2', '\x2', '>', '@', '\n', '\x2', '\x2', '\x2', '?', '>', '\x3', 
		'\x2', '\x2', '\x2', '@', '\x43', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'?', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\x3', '\x2', '\x2', 
		'\x2', '\x42', '\x44', '\x3', '\x2', '\x2', '\x2', '\x43', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x45', '\a', '$', '\x2', '\x2', '\x45', 
		'\x10', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\a', 'v', '\x2', '\x2', 
		'G', 'H', '\a', 't', '\x2', '\x2', 'H', 'I', '\a', 'w', '\x2', '\x2', 
		'I', 'P', '\a', 'g', '\x2', '\x2', 'J', 'K', '\a', 'h', '\x2', '\x2', 
		'K', 'L', '\a', '\x63', '\x2', '\x2', 'L', 'M', '\a', 'n', '\x2', '\x2', 
		'M', 'N', '\a', 'u', '\x2', '\x2', 'N', 'P', '\a', 'g', '\x2', '\x2', 
		'O', '\x46', '\x3', '\x2', '\x2', '\x2', 'O', 'J', '\x3', '\x2', '\x2', 
		'\x2', 'P', '\x12', '\x3', '\x2', '\x2', '\x2', 'Q', 'S', '\t', '\x3', 
		'\x2', '\x2', 'R', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'Y', '\x3', '\x2', '\x2', '\x2', 'V', 'X', '\t', '\x4', 
		'\x2', '\x2', 'W', 'V', '\x3', '\x2', '\x2', '\x2', 'X', '[', '\x3', '\x2', 
		'\x2', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\x3', '\x2', 
		'\x2', '\x2', 'Z', '\x14', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', 
		'\x2', '\x2', '\x2', '\\', '^', '\a', '/', '\x2', '\x2', ']', '\\', '\x3', 
		'\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', 
		'\x2', '\x2', '\x2', '_', '\x66', '\x5', '\x17', '\f', '\x2', '`', '\x62', 
		'\a', '\x30', '\x2', '\x2', '\x61', '\x63', '\t', '\x5', '\x2', '\x2', 
		'\x62', '\x61', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x62', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', 
		'\x3', '\x2', '\x2', '\x2', '\x65', 'g', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'`', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\x3', '\x2', '\x2', '\x2', 
		'g', 'i', '\x3', '\x2', '\x2', '\x2', 'h', 'j', '\x5', '\x19', '\r', '\x2', 
		'i', 'h', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\x3', '\x2', '\x2', '\x2', 
		'j', '\x16', '\x3', '\x2', '\x2', '\x2', 'k', 't', '\a', '\x32', '\x2', 
		'\x2', 'l', 'p', '\t', '\x6', '\x2', '\x2', 'm', 'o', '\t', '\x5', '\x2', 
		'\x2', 'n', 'm', '\x3', '\x2', '\x2', '\x2', 'o', 'r', '\x3', '\x2', '\x2', 
		'\x2', 'p', 'n', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\x3', '\x2', '\x2', 
		'\x2', 'q', 't', '\x3', '\x2', '\x2', '\x2', 'r', 'p', '\x3', '\x2', '\x2', 
		'\x2', 's', 'k', '\x3', '\x2', '\x2', '\x2', 's', 'l', '\x3', '\x2', '\x2', 
		'\x2', 't', '\x18', '\x3', '\x2', '\x2', '\x2', 'u', 'w', '\t', '\a', 
		'\x2', '\x2', 'v', 'x', '\t', '\b', '\x2', '\x2', 'w', 'v', '\x3', '\x2', 
		'\x2', '\x2', 'w', 'x', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\x3', '\x2', 
		'\x2', '\x2', 'y', 'z', '\x5', '\x17', '\f', '\x2', 'z', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '{', '|', '\t', '\t', '\x2', '\x2', '|', '}', '\x3', 
		'\x2', '\x2', '\x2', '}', '~', '\b', '\xE', '\x2', '\x2', '~', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\t', '\n', '\x2', '\x2', 
		'\x80', '\x81', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\b', '\xF', 
		'\x2', '\x2', '\x82', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', 
		'\a', '\x31', '\x2', '\x2', '\x84', '\x85', '\a', ',', '\x2', '\x2', '\x85', 
		'\x86', '\a', ',', '\x2', '\x2', '\x86', '\x8A', '\x3', '\x2', '\x2', 
		'\x2', '\x87', '\x89', '\v', '\x2', '\x2', '\x2', '\x88', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x90', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8A', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x8E', '\a', ',', '\x2', '\x2', '\x8E', 
		'\x91', '\a', '\x31', '\x2', '\x2', '\x8F', '\x91', '\a', '\x2', '\x2', 
		'\x3', '\x90', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x90', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x92', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x93', '\b', '\x10', '\x2', '\x2', '\x93', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x95', '\a', '\x31', '\x2', '\x2', '\x95', '\x96', '\a', 
		',', '\x2', '\x2', '\x96', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x97', 
		'\x99', '\v', '\x2', '\x2', '\x2', '\x98', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '\x99', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9B', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '\x9D', '\x9E', '\a', ',', '\x2', '\x2', '\x9E', '\xA1', '\a', 
		'\x31', '\x2', '\x2', '\x9F', '\xA1', '\a', '\x2', '\x2', '\x3', '\xA0', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\b', 
		'\x11', '\x2', '\x2', '\xA3', '\"', '\x3', '\x2', '\x2', '\x2', '\xA4', 
		'\xA5', '\a', '\x31', '\x2', '\x2', '\xA5', '\xA6', '\a', '\x31', '\x2', 
		'\x2', '\xA6', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA9', '\n', 
		'\v', '\x2', '\x2', '\xA8', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA9', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xA8', '\x3', '\x2', '\x2', 
		'\x2', '\xAA', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAD', 
		'\xAE', '\b', '\x12', '\x2', '\x2', '\xAE', '$', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB0', '\a', '\x31', '\x2', '\x2', '\xB0', '\xB1', '\a', 
		'\x31', '\x2', '\x2', '\xB1', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB2', 
		'\xB4', '\n', '\f', '\x2', '\x2', '\xB3', '\xB2', '\x3', '\x2', '\x2', 
		'\x2', '\xB4', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB3', '\x3', 
		'\x2', '\x2', '\x2', '\xB5', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB6', 
		'\xCA', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB5', '\x3', '\x2', '\x2', 
		'\x2', '\xB8', '\xBC', '\a', '\f', '\x2', '\x2', '\xB9', '\xBB', '\x5', 
		'\x1B', '\xE', '\x2', '\xBA', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xBE', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBA', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBF', 
		'\xC0', '\a', '\x31', '\x2', '\x2', '\xC0', '\xC1', '\a', '\x31', '\x2', 
		'\x2', '\xC1', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC4', '\n', 
		'\f', '\x2', '\x2', '\xC3', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC4', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xC5', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC9', '\x3', 
		'\x2', '\x2', '\x2', '\xC7', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC8', 
		'\xB8', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCC', '\x3', '\x2', '\x2', 
		'\x2', '\xCA', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCC', 
		'\xCA', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCE', '\b', '\x13', '\x2', 
		'\x2', '\xCE', '&', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x2', ':', '\x41', 
		'O', 'R', 'T', 'W', 'Y', ']', '\x64', '\x66', 'i', 'p', 's', 'w', '\x8A', 
		'\x90', '\x9A', '\xA0', '\xAA', '\xB5', '\xBC', '\xC5', '\xCA', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Shiba.Parser
