//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Shiba.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Shiba.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ShibaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, STRING=7, BOOLEAN=8, TOKEN=9, 
		NUMBER=10, Hws=11, Vws=12, DocComment=13, BlockComment=14, LineComment=15, 
		LineCommentExt=16;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "STRING", "BOOLEAN", "TOKEN", 
		"NUMBER", "INT", "EXP", "Hws", "Vws", "DocComment", "BlockComment", "LineComment", 
		"LineCommentExt"
	};


	public ShibaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ShibaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'{'", "','", "'}'", "':'", "'null'", "'%'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, "STRING", "BOOLEAN", "TOKEN", 
		"NUMBER", "Hws", "Vws", "DocComment", "BlockComment", "LineComment", "LineCommentExt"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Shiba.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ShibaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x12', '\xC8', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\a', '\b', '\x39', '\n', '\b', '\f', '\b', 
		'\xE', '\b', '<', '\v', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x5', '\t', 'I', '\n', '\t', '\x3', '\n', '\x6', 
		'\n', 'L', '\n', '\n', '\r', '\n', '\xE', '\n', 'M', '\x3', '\n', '\a', 
		'\n', 'Q', '\n', '\n', '\f', '\n', '\xE', '\n', 'T', '\v', '\n', '\x3', 
		'\v', '\x5', '\v', 'W', '\n', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x6', '\v', '\\', '\n', '\v', '\r', '\v', '\xE', '\v', ']', '\x5', '\v', 
		'`', '\n', '\v', '\x3', '\v', '\x5', '\v', '\x63', '\n', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\a', '\f', 'h', '\n', '\f', '\f', '\f', 
		'\xE', '\f', 'k', '\v', '\f', '\x5', '\f', 'm', '\n', '\f', '\x3', '\r', 
		'\x3', '\r', '\x5', '\r', 'q', '\n', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\a', '\x10', '\x82', '\n', '\x10', 
		'\f', '\x10', '\xE', '\x10', '\x85', '\v', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x5', '\x10', '\x8A', '\n', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\a', '\x11', '\x92', '\n', '\x11', '\f', '\x11', '\xE', '\x11', '\x95', 
		'\v', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', 
		'\x9A', '\n', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '\xA2', '\n', '\x12', 
		'\f', '\x12', '\xE', '\x12', '\xA5', '\v', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\a', 
		'\x13', '\xAD', '\n', '\x13', '\f', '\x13', '\xE', '\x13', '\xB0', '\v', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\xB4', '\n', '\x13', 
		'\f', '\x13', '\xE', '\x13', '\xB7', '\v', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\xBD', '\n', '\x13', 
		'\f', '\x13', '\xE', '\x13', '\xC0', '\v', '\x13', '\a', '\x13', '\xC2', 
		'\n', '\x13', '\f', '\x13', '\xE', '\x13', '\xC5', '\v', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x4', '\x83', '\x93', '\x2', '\x14', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\x2', '\x19', 
		'\x2', '\x1B', '\r', '\x1D', '\xE', '\x1F', '\xF', '!', '\x10', '#', '\x11', 
		'%', '\x12', '\x3', '\x2', '\r', '\x3', '\x2', '$', '$', '\x5', '\x2', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\a', '\x2', '\x30', '\x30', 
		'\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', 
		'\x32', ';', '\x3', '\x2', '\x33', ';', '\x4', '\x2', 'G', 'G', 'g', 'g', 
		'\x4', '\x2', '-', '-', '/', '/', '\x4', '\x2', '\v', '\v', '\"', '\"', 
		'\x4', '\x2', '\f', '\f', '\xE', '\xF', '\x4', '\x2', '\f', '\f', '\xF', 
		'\xF', '\x3', '\x2', '\f', '\f', '\x2', '\xD9', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x3', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x5', ')', '\x3', '\x2', '\x2', '\x2', '\a', '+', 
		'\x3', '\x2', '\x2', '\x2', '\t', '-', '\x3', '\x2', '\x2', '\x2', '\v', 
		'/', '\x3', '\x2', '\x2', '\x2', '\r', '\x34', '\x3', '\x2', '\x2', '\x2', 
		'\xF', '\x36', '\x3', '\x2', '\x2', '\x2', '\x11', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\x13', 'K', '\x3', '\x2', '\x2', '\x2', '\x15', 'V', '\x3', 
		'\x2', '\x2', '\x2', '\x17', 'l', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'n', '\x3', '\x2', '\x2', '\x2', '\x1B', 't', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', 'x', '\x3', '\x2', '\x2', '\x2', '\x1F', '|', '\x3', '\x2', '\x2', 
		'\x2', '!', '\x8D', '\x3', '\x2', '\x2', '\x2', '#', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '%', '\xA8', '\x3', '\x2', '\x2', '\x2', '\'', '(', '\a', 
		'}', '\x2', '\x2', '(', '\x4', '\x3', '\x2', '\x2', '\x2', ')', '*', '\a', 
		'.', '\x2', '\x2', '*', '\x6', '\x3', '\x2', '\x2', '\x2', '+', ',', '\a', 
		'\x7F', '\x2', '\x2', ',', '\b', '\x3', '\x2', '\x2', '\x2', '-', '.', 
		'\a', '<', '\x2', '\x2', '.', '\n', '\x3', '\x2', '\x2', '\x2', '/', '\x30', 
		'\a', 'p', '\x2', '\x2', '\x30', '\x31', '\a', 'w', '\x2', '\x2', '\x31', 
		'\x32', '\a', 'n', '\x2', '\x2', '\x32', '\x33', '\a', 'n', '\x2', '\x2', 
		'\x33', '\f', '\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\a', '\'', 
		'\x2', '\x2', '\x35', '\xE', '\x3', '\x2', '\x2', '\x2', '\x36', ':', 
		'\a', '$', '\x2', '\x2', '\x37', '\x39', '\n', '\x2', '\x2', '\x2', '\x38', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x39', '<', '\x3', '\x2', '\x2', 
		'\x2', ':', '\x38', '\x3', '\x2', '\x2', '\x2', ':', ';', '\x3', '\x2', 
		'\x2', '\x2', ';', '=', '\x3', '\x2', '\x2', '\x2', '<', ':', '\x3', '\x2', 
		'\x2', '\x2', '=', '>', '\a', '$', '\x2', '\x2', '>', '\x10', '\x3', '\x2', 
		'\x2', '\x2', '?', '@', '\a', 'v', '\x2', '\x2', '@', '\x41', '\a', 't', 
		'\x2', '\x2', '\x41', '\x42', '\a', 'w', '\x2', '\x2', '\x42', 'I', '\a', 
		'g', '\x2', '\x2', '\x43', '\x44', '\a', 'h', '\x2', '\x2', '\x44', '\x45', 
		'\a', '\x63', '\x2', '\x2', '\x45', '\x46', '\a', 'n', '\x2', '\x2', '\x46', 
		'G', '\a', 'u', '\x2', '\x2', 'G', 'I', '\a', 'g', '\x2', '\x2', 'H', 
		'?', '\x3', '\x2', '\x2', '\x2', 'H', '\x43', '\x3', '\x2', '\x2', '\x2', 
		'I', '\x12', '\x3', '\x2', '\x2', '\x2', 'J', 'L', '\t', '\x3', '\x2', 
		'\x2', 'K', 'J', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'K', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'R', '\x3', '\x2', '\x2', '\x2', 'O', 'Q', '\t', '\x4', '\x2', 
		'\x2', 'P', 'O', '\x3', '\x2', '\x2', '\x2', 'Q', 'T', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', 
		'\x2', 'S', '\x14', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'W', '\a', '/', '\x2', '\x2', 'V', 'U', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', 
		'\x2', '\x2', 'X', '_', '\x5', '\x17', '\f', '\x2', 'Y', '[', '\a', '\x30', 
		'\x2', '\x2', 'Z', '\\', '\t', '\x5', '\x2', '\x2', '[', 'Z', '\x3', '\x2', 
		'\x2', '\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', 
		'\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', '^', '`', '\x3', 
		'\x2', '\x2', '\x2', '_', 'Y', '\x3', '\x2', '\x2', '\x2', '_', '`', '\x3', 
		'\x2', '\x2', '\x2', '`', '\x62', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'\x63', '\x5', '\x19', '\r', '\x2', '\x62', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x63', '\x3', '\x2', '\x2', '\x2', '\x63', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x64', 'm', '\a', '\x32', '\x2', '\x2', '\x65', 
		'i', '\t', '\x6', '\x2', '\x2', '\x66', 'h', '\t', '\x5', '\x2', '\x2', 
		'g', '\x66', '\x3', '\x2', '\x2', '\x2', 'h', 'k', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'g', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\x3', '\x2', '\x2', 
		'\x2', 'j', 'm', '\x3', '\x2', '\x2', '\x2', 'k', 'i', '\x3', '\x2', '\x2', 
		'\x2', 'l', '\x64', '\x3', '\x2', '\x2', '\x2', 'l', '\x65', '\x3', '\x2', 
		'\x2', '\x2', 'm', '\x18', '\x3', '\x2', '\x2', '\x2', 'n', 'p', '\t', 
		'\a', '\x2', '\x2', 'o', 'q', '\t', '\b', '\x2', '\x2', 'p', 'o', '\x3', 
		'\x2', '\x2', '\x2', 'p', 'q', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\x3', 
		'\x2', '\x2', '\x2', 'r', 's', '\x5', '\x17', '\f', '\x2', 's', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', 't', 'u', '\t', '\t', '\x2', '\x2', 'u', 'v', 
		'\x3', '\x2', '\x2', '\x2', 'v', 'w', '\b', '\xE', '\x2', '\x2', 'w', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\t', '\n', '\x2', '\x2', 
		'y', 'z', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\b', '\xF', '\x2', '\x2', 
		'{', '\x1E', '\x3', '\x2', '\x2', '\x2', '|', '}', '\a', '\x31', '\x2', 
		'\x2', '}', '~', '\a', ',', '\x2', '\x2', '~', '\x7F', '\a', ',', '\x2', 
		'\x2', '\x7F', '\x83', '\x3', '\x2', '\x2', '\x2', '\x80', '\x82', '\v', 
		'\x2', '\x2', '\x2', '\x81', '\x80', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x85', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x81', '\x3', '\x2', '\x2', '\x2', '\x84', '\x89', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'\x87', '\a', ',', '\x2', '\x2', '\x87', '\x8A', '\a', '\x31', '\x2', 
		'\x2', '\x88', '\x8A', '\a', '\x2', '\x2', '\x3', '\x89', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\b', '\x10', '\x2', 
		'\x2', '\x8C', ' ', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'\x31', '\x2', '\x2', '\x8E', '\x8F', '\a', ',', '\x2', '\x2', '\x8F', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x90', '\x92', '\v', '\x2', '\x2', 
		'\x2', '\x91', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x93', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x94', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x93', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\a', 
		',', '\x2', '\x2', '\x97', '\x9A', '\a', '\x31', '\x2', '\x2', '\x98', 
		'\x9A', '\a', '\x2', '\x2', '\x3', '\x99', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '\x99', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9B', '\x9C', '\b', '\x11', '\x2', '\x2', '\x9C', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\a', '\x31', '\x2', 
		'\x2', '\x9E', '\x9F', '\a', '\x31', '\x2', '\x2', '\x9F', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA2', '\n', '\v', '\x2', '\x2', '\xA1', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA4', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\b', '\x12', '\x2', 
		'\x2', '\xA7', '$', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\a', 
		'\x31', '\x2', '\x2', '\xA9', '\xAA', '\a', '\x31', '\x2', '\x2', '\xAA', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAD', '\n', '\f', '\x2', 
		'\x2', '\xAC', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xB0', '\x3', 
		'\x2', '\x2', '\x2', '\xAE', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xB0', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB5', '\a', 
		'\f', '\x2', '\x2', '\xB2', '\xB4', '\x5', '\x1B', '\xE', '\x2', '\xB3', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xB5', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xB7', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', '\a', '\x31', '\x2', 
		'\x2', '\xB9', '\xBA', '\a', '\x31', '\x2', '\x2', '\xBA', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\xBB', '\xBD', '\n', '\f', '\x2', '\x2', '\xBC', 
		'\xBB', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xBF', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xBE', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xC2', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\xC3', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC4', 
		'\xC6', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xC7', '\b', '\x13', '\x2', '\x2', '\xC7', '&', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '\x2', ':', 'H', 'K', 'M', 'P', 'R', 'V', 
		']', '_', '\x62', 'i', 'l', 'p', '\x83', '\x89', '\x93', '\x99', '\xA3', 
		'\xAE', '\xB5', '\xBE', '\xC3', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Shiba.Parser
