//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Shiba.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Shiba.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ShibaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, STRING=6, BOOLEAN=7, TOKEN=8, 
		NUMBER=9, Hws=10, Vws=11, DocComment=12, BlockComment=13, LineComment=14, 
		LineCommentExt=15;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "STRING", "BOOLEAN", "TOKEN", 
		"NUMBER", "INT", "EXP", "Hws", "Vws", "DocComment", "BlockComment", "LineComment", 
		"LineCommentExt"
	};


	public ShibaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ShibaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'{'", "','", "'}'", "':'", "'null'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, "STRING", "BOOLEAN", "TOKEN", "NUMBER", 
		"Hws", "Vws", "DocComment", "BlockComment", "LineComment", "LineCommentExt"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Shiba.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ShibaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x11', '\xC4', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\a', '\a', '\x35', '\n', 
		'\a', '\f', '\a', '\xE', '\a', '\x38', '\v', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', '\x45', 
		'\n', '\b', '\x3', '\t', '\x6', '\t', 'H', '\n', '\t', '\r', '\t', '\xE', 
		'\t', 'I', '\x3', '\t', '\a', '\t', 'M', '\n', '\t', '\f', '\t', '\xE', 
		'\t', 'P', '\v', '\t', '\x3', '\n', '\x5', '\n', 'S', '\n', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x6', '\n', 'X', '\n', '\n', '\r', '\n', 
		'\xE', '\n', 'Y', '\x5', '\n', '\\', '\n', '\n', '\x3', '\n', '\x5', '\n', 
		'_', '\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\a', '\v', '\x64', 
		'\n', '\v', '\f', '\v', '\xE', '\v', 'g', '\v', '\v', '\x5', '\v', 'i', 
		'\n', '\v', '\x3', '\f', '\x3', '\f', '\x5', '\f', 'm', '\n', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\a', '\xF', '~', 
		'\n', '\xF', '\f', '\xF', '\xE', '\xF', '\x81', '\v', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x5', '\xF', '\x86', '\n', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\a', '\x10', '\x8E', '\n', '\x10', '\f', '\x10', '\xE', '\x10', 
		'\x91', '\v', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', 
		'\x10', '\x96', '\n', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', '\x9E', '\n', 
		'\x11', '\f', '\x11', '\xE', '\x11', '\xA1', '\v', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\a', '\x12', '\xA9', '\n', '\x12', '\f', '\x12', '\xE', '\x12', '\xAC', 
		'\v', '\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '\xB0', '\n', 
		'\x12', '\f', '\x12', '\xE', '\x12', '\xB3', '\v', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '\xB9', '\n', 
		'\x12', '\f', '\x12', '\xE', '\x12', '\xBC', '\v', '\x12', '\a', '\x12', 
		'\xBE', '\n', '\x12', '\f', '\x12', '\xE', '\x12', '\xC1', '\v', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x4', '\x7F', '\x8F', '\x2', '\x13', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\x2', '\x17', '\x2', 
		'\x19', '\f', '\x1B', '\r', '\x1D', '\xE', '\x1F', '\xF', '!', '\x10', 
		'#', '\x11', '\x3', '\x2', '\r', '\x3', '\x2', '$', '$', '\x5', '\x2', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', '\x32', ';', 
		'\x3', '\x2', '\x33', ';', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', '\x2', 
		'-', '-', '/', '/', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x4', '\x2', 
		'\f', '\f', '\xE', '\xF', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x3', 
		'\x2', '\f', '\f', '\x2', '\xD5', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '%', '\x3', '\x2', '\x2', '\x2', '\x5', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\a', ')', '\x3', '\x2', '\x2', '\x2', '\t', '+', '\x3', '\x2', 
		'\x2', '\x2', '\v', '-', '\x3', '\x2', '\x2', '\x2', '\r', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\xF', '\x44', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'G', '\x3', '\x2', '\x2', '\x2', '\x13', 'R', '\x3', '\x2', '\x2', '\x2', 
		'\x15', 'h', '\x3', '\x2', '\x2', '\x2', '\x17', 'j', '\x3', '\x2', '\x2', 
		'\x2', '\x19', 'p', '\x3', '\x2', '\x2', '\x2', '\x1B', 't', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', 'x', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x89', 
		'\x3', '\x2', '\x2', '\x2', '!', '\x99', '\x3', '\x2', '\x2', '\x2', '#', 
		'\xA4', '\x3', '\x2', '\x2', '\x2', '%', '&', '\a', '}', '\x2', '\x2', 
		'&', '\x4', '\x3', '\x2', '\x2', '\x2', '\'', '(', '\a', '.', '\x2', '\x2', 
		'(', '\x6', '\x3', '\x2', '\x2', '\x2', ')', '*', '\a', '\x7F', '\x2', 
		'\x2', '*', '\b', '\x3', '\x2', '\x2', '\x2', '+', ',', '\a', '<', '\x2', 
		'\x2', ',', '\n', '\x3', '\x2', '\x2', '\x2', '-', '.', '\a', 'p', '\x2', 
		'\x2', '.', '/', '\a', 'w', '\x2', '\x2', '/', '\x30', '\a', 'n', '\x2', 
		'\x2', '\x30', '\x31', '\a', 'n', '\x2', '\x2', '\x31', '\f', '\x3', '\x2', 
		'\x2', '\x2', '\x32', '\x36', '\a', '$', '\x2', '\x2', '\x33', '\x35', 
		'\n', '\x2', '\x2', '\x2', '\x34', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x38', '\x3', '\x2', '\x2', '\x2', '\x36', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\x36', '\x37', '\x3', '\x2', '\x2', '\x2', '\x37', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x38', '\x36', '\x3', '\x2', '\x2', '\x2', 
		'\x39', ':', '\a', '$', '\x2', '\x2', ':', '\xE', '\x3', '\x2', '\x2', 
		'\x2', ';', '<', '\a', 'v', '\x2', '\x2', '<', '=', '\a', 't', '\x2', 
		'\x2', '=', '>', '\a', 'w', '\x2', '\x2', '>', '\x45', '\a', 'g', '\x2', 
		'\x2', '?', '@', '\a', 'h', '\x2', '\x2', '@', '\x41', '\a', '\x63', '\x2', 
		'\x2', '\x41', '\x42', '\a', 'n', '\x2', '\x2', '\x42', '\x43', '\a', 
		'u', '\x2', '\x2', '\x43', '\x45', '\a', 'g', '\x2', '\x2', '\x44', ';', 
		'\x3', '\x2', '\x2', '\x2', '\x44', '?', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x10', '\x3', '\x2', '\x2', '\x2', '\x46', 'H', '\t', '\x3', '\x2', '\x2', 
		'G', '\x46', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'G', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\x3', '\x2', '\x2', 
		'\x2', 'J', 'N', '\x3', '\x2', '\x2', '\x2', 'K', 'M', '\t', '\x4', '\x2', 
		'\x2', 'L', 'K', '\x3', '\x2', '\x2', '\x2', 'M', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'L', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\x3', '\x2', '\x2', 
		'\x2', 'O', '\x12', '\x3', '\x2', '\x2', '\x2', 'P', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'S', '\a', '/', '\x2', '\x2', 'R', 'Q', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'T', '[', '\x5', '\x15', '\v', '\x2', 'U', 'W', '\a', '\x30', 
		'\x2', '\x2', 'V', 'X', '\t', '\x5', '\x2', '\x2', 'W', 'V', '\x3', '\x2', 
		'\x2', '\x2', 'X', 'Y', '\x3', '\x2', '\x2', '\x2', 'Y', 'W', '\x3', '\x2', 
		'\x2', '\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', '\\', '\x3', 
		'\x2', '\x2', '\x2', '[', 'U', '\x3', '\x2', '\x2', '\x2', '[', '\\', 
		'\x3', '\x2', '\x2', '\x2', '\\', '^', '\x3', '\x2', '\x2', '\x2', ']', 
		'_', '\x5', '\x17', '\f', '\x2', '^', ']', '\x3', '\x2', '\x2', '\x2', 
		'^', '_', '\x3', '\x2', '\x2', '\x2', '_', '\x14', '\x3', '\x2', '\x2', 
		'\x2', '`', 'i', '\a', '\x32', '\x2', '\x2', '\x61', '\x65', '\t', '\x6', 
		'\x2', '\x2', '\x62', '\x64', '\t', '\x5', '\x2', '\x2', '\x63', '\x62', 
		'\x3', '\x2', '\x2', '\x2', '\x64', 'g', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'i', '\x3', '\x2', '\x2', '\x2', 'g', '\x65', '\x3', '\x2', 
		'\x2', '\x2', 'h', '`', '\x3', '\x2', '\x2', '\x2', 'h', '\x61', '\x3', 
		'\x2', '\x2', '\x2', 'i', '\x16', '\x3', '\x2', '\x2', '\x2', 'j', 'l', 
		'\t', '\a', '\x2', '\x2', 'k', 'm', '\t', '\b', '\x2', '\x2', 'l', 'k', 
		'\x3', '\x2', '\x2', '\x2', 'l', 'm', '\x3', '\x2', '\x2', '\x2', 'm', 
		'n', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x5', '\x15', '\v', '\x2', 
		'o', '\x18', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\t', '\t', '\x2', 
		'\x2', 'q', 'r', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\b', '\r', '\x2', 
		'\x2', 's', '\x1A', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\t', '\n', 
		'\x2', '\x2', 'u', 'v', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\b', '\xE', 
		'\x2', '\x2', 'w', '\x1C', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\a', 
		'\x31', '\x2', '\x2', 'y', 'z', '\a', ',', '\x2', '\x2', 'z', '{', '\a', 
		',', '\x2', '\x2', '{', '\x7F', '\x3', '\x2', '\x2', '\x2', '|', '~', 
		'\v', '\x2', '\x2', '\x2', '}', '|', '\x3', '\x2', '\x2', '\x2', '~', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '}', '\x3', '\x2', '\x2', '\x2', '\x80', '\x85', '\x3', 
		'\x2', '\x2', '\x2', '\x81', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x83', '\a', ',', '\x2', '\x2', '\x83', '\x86', '\a', '\x31', '\x2', 
		'\x2', '\x84', '\x86', '\a', '\x2', '\x2', '\x3', '\x85', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x84', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\b', '\xF', '\x2', 
		'\x2', '\x88', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\a', 
		'\x31', '\x2', '\x2', '\x8A', '\x8B', '\a', ',', '\x2', '\x2', '\x8B', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8E', '\v', '\x2', '\x2', 
		'\x2', '\x8D', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x90', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x91', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\a', 
		',', '\x2', '\x2', '\x93', '\x96', '\a', '\x31', '\x2', '\x2', '\x94', 
		'\x96', '\a', '\x2', '\x2', '\x3', '\x95', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x94', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x98', '\b', '\x10', '\x2', '\x2', '\x98', 
		' ', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '\x31', '\x2', 
		'\x2', '\x9A', '\x9B', '\a', '\x31', '\x2', '\x2', '\x9B', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9E', '\n', '\v', '\x2', '\x2', '\x9D', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x9E', '\xA1', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\x9F', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\b', '\x11', '\x2', 
		'\x2', '\xA3', '\"', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', 
		'\x31', '\x2', '\x2', '\xA5', '\xA6', '\a', '\x31', '\x2', '\x2', '\xA6', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA9', '\n', '\f', '\x2', 
		'\x2', '\xA8', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAC', '\x3', 
		'\x2', '\x2', '\x2', '\xAA', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xBF', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xB1', '\a', 
		'\f', '\x2', '\x2', '\xAE', '\xB0', '\x5', '\x19', '\r', '\x2', '\xAF', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB3', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\x3', 
		'\x2', '\x2', '\x2', '\xB2', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB3', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\a', '\x31', '\x2', 
		'\x2', '\xB5', '\xB6', '\a', '\x31', '\x2', '\x2', '\xB6', '\xBA', '\x3', 
		'\x2', '\x2', '\x2', '\xB7', '\xB9', '\n', '\f', '\x2', '\x2', '\xB8', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', '\xBA', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\x3', 
		'\x2', '\x2', '\x2', '\xBB', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\xBA', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\xBF', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xC2', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xBF', '\x3', '\x2', '\x2', 
		'\x2', '\xC2', '\xC3', '\b', '\x12', '\x2', '\x2', '\xC3', '$', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '\x2', '\x36', '\x44', 'G', 'I', 'L', 'N', 
		'R', 'Y', '[', '^', '\x65', 'h', 'l', '\x7F', '\x85', '\x8F', '\x95', 
		'\x9F', '\xAA', '\xB1', '\xBA', '\xBF', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Shiba.Parser
