//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Shiba.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Shiba.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ShibaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IShibaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot([NotNull] ShibaParser.RootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot([NotNull] ShibaParser.RootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObj([NotNull] ShibaParser.ObjContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObj([NotNull] ShibaParser.ObjContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] ShibaParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] ShibaParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ShibaParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ShibaParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.staticvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticvalue([NotNull] ShibaParser.StaticvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.staticvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticvalue([NotNull] ShibaParser.StaticvalueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.percent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPercent([NotNull] ShibaParser.PercentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.percent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPercent([NotNull] ShibaParser.PercentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.thickness"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThickness([NotNull] ShibaParser.ThicknessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.thickness"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThickness([NotNull] ShibaParser.ThicknessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.calc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCalc([NotNull] ShibaParser.CalcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.calc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCalc([NotNull] ShibaParser.CalcContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] ShibaParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] ShibaParser.FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.paramter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamter([NotNull] ShibaParser.ParamterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.paramter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamter([NotNull] ShibaParser.ParamterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinding([NotNull] ShibaParser.BindingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinding([NotNull] ShibaParser.BindingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResource([NotNull] ShibaParser.ResourceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResource([NotNull] ShibaParser.ResourceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.jsonpath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonpath([NotNull] ShibaParser.JsonpathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.jsonpath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonpath([NotNull] ShibaParser.JsonpathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.dic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDic([NotNull] ShibaParser.DicContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.dic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDic([NotNull] ShibaParser.DicContext context);
}
} // namespace Shiba.Parser
