//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Shiba.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Shiba.Parser {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ShibaParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, NULL=14, STRING=15, BOOLEAN=16, 
		TOKEN=17, NUMBER=18, Hws=19, Vws=20, DocComment=21, BlockComment=22, LineComment=23, 
		LineCommentExt=24;
	public const int
		RULE_root = 0, RULE_obj = 1, RULE_pair = 2, RULE_value = 3, RULE_staticvalue = 4, 
		RULE_percent = 5, RULE_thickness = 6, RULE_func = 7, RULE_paramter = 8, 
		RULE_binding = 9, RULE_resource = 10, RULE_jsonpath = 11, RULE_dic = 12;
	public static readonly string[] ruleNames = {
		"root", "obj", "pair", "value", "staticvalue", "percent", "thickness", 
		"func", "paramter", "binding", "resource", "jsonpath", "dic"
	};

	private static readonly string[] _LiteralNames = {
		null, "'{'", "','", "'}'", "':'", "'='", "'%'", "'['", "']'", "'('", "')'", 
		"'$bind'", "'$res'", "'$json'", "'null'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "NULL", "STRING", "BOOLEAN", "TOKEN", "NUMBER", "Hws", "Vws", 
		"DocComment", "BlockComment", "LineComment", "LineCommentExt"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Shiba.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ShibaParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ShibaParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ShibaParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class RootContext : ParserRuleContext {
		public ObjContext obj() {
			return GetRuleContext<ObjContext>(0);
		}
		public RootContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_root; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterRoot(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitRoot(this);
		}
	}

	[RuleVersion(0)]
	public RootContext root() {
		RootContext _localctx = new RootContext(Context, State);
		EnterRule(_localctx, 0, RULE_root);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 26; obj();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjContext : ParserRuleContext {
		public ITerminalNode TOKEN() { return GetToken(ShibaParser.TOKEN, 0); }
		public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public ObjContext[] obj() {
			return GetRuleContexts<ObjContext>();
		}
		public ObjContext obj(int i) {
			return GetRuleContext<ObjContext>(i);
		}
		public ObjContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_obj; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterObj(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitObj(this);
		}
	}

	[RuleVersion(0)]
	public ObjContext obj() {
		ObjContext _localctx = new ObjContext(Context, State);
		EnterRule(_localctx, 2, RULE_obj);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 28; Match(TOKEN);
			State = 49;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__0) {
				{
				State = 29; Match(T__0);
				State = 46;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==TOKEN) {
					{
					State = 32;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
					case 1:
						{
						State = 30; pair();
						}
						break;
					case 2:
						{
						State = 31; obj();
						}
						break;
					}
					State = 43;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__1 || _la==TOKEN) {
						{
						{
						State = 35;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if (_la==T__1) {
							{
							State = 34; Match(T__1);
							}
						}

						State = 39;
						ErrorHandler.Sync(this);
						switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
						case 1:
							{
							State = 37; pair();
							}
							break;
						case 2:
							{
							State = 38; obj();
							}
							break;
						}
						}
						}
						State = 45;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 48; Match(T__2);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PairContext : ParserRuleContext {
		public ITerminalNode TOKEN() { return GetToken(ShibaParser.TOKEN, 0); }
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public PairContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pair; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterPair(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitPair(this);
		}
	}

	[RuleVersion(0)]
	public PairContext pair() {
		PairContext _localctx = new PairContext(Context, State);
		EnterRule(_localctx, 4, RULE_pair);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51; Match(TOKEN);
			State = 52;
			_la = TokenStream.LA(1);
			if ( !(_la==T__3 || _la==T__4) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 53; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public StaticvalueContext staticvalue() {
			return GetRuleContext<StaticvalueContext>(0);
		}
		public BindingContext binding() {
			return GetRuleContext<BindingContext>(0);
		}
		public ResourceContext resource() {
			return GetRuleContext<ResourceContext>(0);
		}
		public JsonpathContext jsonpath() {
			return GetRuleContext<JsonpathContext>(0);
		}
		public FuncContext func() {
			return GetRuleContext<FuncContext>(0);
		}
		public DicContext dic() {
			return GetRuleContext<DicContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 6, RULE_value);
		try {
			State = 61;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 55; staticvalue();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 56; binding();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 57; resource();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 58; jsonpath();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 59; func();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 60; dic();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StaticvalueContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(ShibaParser.STRING, 0); }
		public ITerminalNode NUMBER() { return GetToken(ShibaParser.NUMBER, 0); }
		public ITerminalNode BOOLEAN() { return GetToken(ShibaParser.BOOLEAN, 0); }
		public ITerminalNode NULL() { return GetToken(ShibaParser.NULL, 0); }
		public ITerminalNode TOKEN() { return GetToken(ShibaParser.TOKEN, 0); }
		public PercentContext percent() {
			return GetRuleContext<PercentContext>(0);
		}
		public ThicknessContext thickness() {
			return GetRuleContext<ThicknessContext>(0);
		}
		public StaticvalueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_staticvalue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterStaticvalue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitStaticvalue(this);
		}
	}

	[RuleVersion(0)]
	public StaticvalueContext staticvalue() {
		StaticvalueContext _localctx = new StaticvalueContext(Context, State);
		EnterRule(_localctx, 8, RULE_staticvalue);
		try {
			State = 70;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 63; Match(STRING);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 64; Match(NUMBER);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 65; Match(BOOLEAN);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 66; Match(NULL);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 67; Match(TOKEN);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 68; percent();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 69; thickness();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PercentContext : ParserRuleContext {
		public ITerminalNode NUMBER() { return GetToken(ShibaParser.NUMBER, 0); }
		public PercentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_percent; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterPercent(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitPercent(this);
		}
	}

	[RuleVersion(0)]
	public PercentContext percent() {
		PercentContext _localctx = new PercentContext(Context, State);
		EnterRule(_localctx, 10, RULE_percent);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 72; Match(NUMBER);
			State = 73; Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ThicknessContext : ParserRuleContext {
		public ITerminalNode[] NUMBER() { return GetTokens(ShibaParser.NUMBER); }
		public ITerminalNode NUMBER(int i) {
			return GetToken(ShibaParser.NUMBER, i);
		}
		public ThicknessContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_thickness; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterThickness(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitThickness(this);
		}
	}

	[RuleVersion(0)]
	public ThicknessContext thickness() {
		ThicknessContext _localctx = new ThicknessContext(Context, State);
		EnterRule(_localctx, 12, RULE_thickness);
		try {
			State = 92;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 75; Match(T__6);
				State = 76; Match(NUMBER);
				State = 77; Match(T__7);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 78; Match(T__6);
				State = 79; Match(NUMBER);
				State = 80; Match(T__1);
				State = 81; Match(NUMBER);
				State = 82; Match(T__7);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 83; Match(T__6);
				State = 84; Match(NUMBER);
				State = 85; Match(T__1);
				State = 86; Match(NUMBER);
				State = 87; Match(T__1);
				State = 88; Match(NUMBER);
				State = 89; Match(T__1);
				State = 90; Match(NUMBER);
				State = 91; Match(T__7);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FuncContext : ParserRuleContext {
		public ITerminalNode TOKEN() { return GetToken(ShibaParser.TOKEN, 0); }
		public ParamterContext[] paramter() {
			return GetRuleContexts<ParamterContext>();
		}
		public ParamterContext paramter(int i) {
			return GetRuleContext<ParamterContext>(i);
		}
		public FuncContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterFunc(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitFunc(this);
		}
	}

	[RuleVersion(0)]
	public FuncContext func() {
		FuncContext _localctx = new FuncContext(Context, State);
		EnterRule(_localctx, 14, RULE_func);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94; Match(TOKEN);
			State = 95; Match(T__8);
			State = 96; paramter();
			State = 101;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 97; Match(T__1);
				State = 98; paramter();
				}
				}
				State = 103;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 104; Match(T__9);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParamterContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public FuncContext func() {
			return GetRuleContext<FuncContext>(0);
		}
		public ParamterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_paramter; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterParamter(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitParamter(this);
		}
	}

	[RuleVersion(0)]
	public ParamterContext paramter() {
		ParamterContext _localctx = new ParamterContext(Context, State);
		EnterRule(_localctx, 16, RULE_paramter);
		try {
			State = 108;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 106; value();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 107; func();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BindingContext : ParserRuleContext {
		public StaticvalueContext staticvalue() {
			return GetRuleContext<StaticvalueContext>(0);
		}
		public BindingContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binding; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterBinding(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitBinding(this);
		}
	}

	[RuleVersion(0)]
	public BindingContext binding() {
		BindingContext _localctx = new BindingContext(Context, State);
		EnterRule(_localctx, 18, RULE_binding);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 110; Match(T__10);
			State = 111; staticvalue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ResourceContext : ParserRuleContext {
		public StaticvalueContext staticvalue() {
			return GetRuleContext<StaticvalueContext>(0);
		}
		public ResourceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_resource; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterResource(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitResource(this);
		}
	}

	[RuleVersion(0)]
	public ResourceContext resource() {
		ResourceContext _localctx = new ResourceContext(Context, State);
		EnterRule(_localctx, 20, RULE_resource);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113; Match(T__11);
			State = 114; staticvalue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonpathContext : ParserRuleContext {
		public StaticvalueContext staticvalue() {
			return GetRuleContext<StaticvalueContext>(0);
		}
		public JsonpathContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonpath; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterJsonpath(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitJsonpath(this);
		}
	}

	[RuleVersion(0)]
	public JsonpathContext jsonpath() {
		JsonpathContext _localctx = new JsonpathContext(Context, State);
		EnterRule(_localctx, 22, RULE_jsonpath);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116; Match(T__12);
			State = 117; staticvalue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DicContext : ParserRuleContext {
		public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public DicContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dic; } }
		public override void EnterRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.EnterDic(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IShibaListener typedListener = listener as IShibaListener;
			if (typedListener != null) typedListener.ExitDic(this);
		}
	}

	[RuleVersion(0)]
	public DicContext dic() {
		DicContext _localctx = new DicContext(Context, State);
		EnterRule(_localctx, 24, RULE_dic);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119; Match(T__6);
			State = 120; pair();
			State = 127;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1 || _la==TOKEN) {
				{
				{
				State = 122;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__1) {
					{
					State = 121; Match(T__1);
					}
				}

				State = 124; pair();
				}
				}
				State = 129;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 130; Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x1A', '\x87', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x5', '\x3', '#', '\n', '\x3', '\x3', '\x3', '\x5', 
		'\x3', '&', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '*', 
		'\n', '\x3', '\a', '\x3', ',', '\n', '\x3', '\f', '\x3', '\xE', '\x3', 
		'/', '\v', '\x3', '\x5', '\x3', '\x31', '\n', '\x3', '\x3', '\x3', '\x5', 
		'\x3', '\x34', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '@', '\n', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x5', '\x6', 'I', '\n', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x5', '\b', '_', '\n', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\a', '\t', '\x66', '\n', '\t', 
		'\f', '\t', '\xE', '\t', 'i', '\v', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x5', '\n', 'o', '\n', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', 
		'}', '\n', '\xE', '\x3', '\xE', '\a', '\xE', '\x80', '\n', '\xE', '\f', 
		'\xE', '\xE', '\xE', '\x83', '\v', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x2', '\x2', '\xF', '\x2', '\x4', '\x6', '\b', '\n', '\f', 
		'\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x2', '\x3', '\x3', 
		'\x2', '\x6', '\a', '\x2', '\x90', '\x2', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\x4', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x6', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\b', '?', '\x3', '\x2', '\x2', '\x2', '\n', 'H', 
		'\x3', '\x2', '\x2', '\x2', '\f', 'J', '\x3', '\x2', '\x2', '\x2', '\xE', 
		'^', '\x3', '\x2', '\x2', '\x2', '\x10', '`', '\x3', '\x2', '\x2', '\x2', 
		'\x12', 'n', '\x3', '\x2', '\x2', '\x2', '\x14', 'p', '\x3', '\x2', '\x2', 
		'\x2', '\x16', 's', '\x3', '\x2', '\x2', '\x2', '\x18', 'v', '\x3', '\x2', 
		'\x2', '\x2', '\x1A', 'y', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', 
		'\x5', '\x4', '\x3', '\x2', '\x1D', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', '\x33', '\a', '\x13', '\x2', '\x2', '\x1F', '\x30', '\a', '\x3', 
		'\x2', '\x2', ' ', '#', '\x5', '\x6', '\x4', '\x2', '!', '#', '\x5', '\x4', 
		'\x3', '\x2', '\"', ' ', '\x3', '\x2', '\x2', '\x2', '\"', '!', '\x3', 
		'\x2', '\x2', '\x2', '#', '-', '\x3', '\x2', '\x2', '\x2', '$', '&', '\a', 
		'\x4', '\x2', '\x2', '%', '$', '\x3', '\x2', '\x2', '\x2', '%', '&', '\x3', 
		'\x2', '\x2', '\x2', '&', ')', '\x3', '\x2', '\x2', '\x2', '\'', '*', 
		'\x5', '\x6', '\x4', '\x2', '(', '*', '\x5', '\x4', '\x3', '\x2', ')', 
		'\'', '\x3', '\x2', '\x2', '\x2', ')', '(', '\x3', '\x2', '\x2', '\x2', 
		'*', ',', '\x3', '\x2', '\x2', '\x2', '+', '%', '\x3', '\x2', '\x2', '\x2', 
		',', '/', '\x3', '\x2', '\x2', '\x2', '-', '+', '\x3', '\x2', '\x2', '\x2', 
		'-', '.', '\x3', '\x2', '\x2', '\x2', '.', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '/', '-', '\x3', '\x2', '\x2', '\x2', '\x30', '\"', '\x3', '\x2', 
		'\x2', '\x2', '\x30', '\x31', '\x3', '\x2', '\x2', '\x2', '\x31', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\x32', '\x34', '\a', '\x5', '\x2', '\x2', 
		'\x33', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\x34', '\x5', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', 
		'\a', '\x13', '\x2', '\x2', '\x36', '\x37', '\t', '\x2', '\x2', '\x2', 
		'\x37', '\x38', '\x5', '\b', '\x5', '\x2', '\x38', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '@', '\x5', '\n', '\x6', '\x2', ':', '@', '\x5', 
		'\x14', '\v', '\x2', ';', '@', '\x5', '\x16', '\f', '\x2', '<', '@', '\x5', 
		'\x18', '\r', '\x2', '=', '@', '\x5', '\x10', '\t', '\x2', '>', '@', '\x5', 
		'\x1A', '\xE', '\x2', '?', '\x39', '\x3', '\x2', '\x2', '\x2', '?', ':', 
		'\x3', '\x2', '\x2', '\x2', '?', ';', '\x3', '\x2', '\x2', '\x2', '?', 
		'<', '\x3', '\x2', '\x2', '\x2', '?', '=', '\x3', '\x2', '\x2', '\x2', 
		'?', '>', '\x3', '\x2', '\x2', '\x2', '@', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x41', 'I', '\a', '\x11', '\x2', '\x2', '\x42', 'I', '\a', '\x14', 
		'\x2', '\x2', '\x43', 'I', '\a', '\x12', '\x2', '\x2', '\x44', 'I', '\a', 
		'\x10', '\x2', '\x2', '\x45', 'I', '\a', '\x13', '\x2', '\x2', '\x46', 
		'I', '\x5', '\f', '\a', '\x2', 'G', 'I', '\x5', '\xE', '\b', '\x2', 'H', 
		'\x41', '\x3', '\x2', '\x2', '\x2', 'H', '\x42', '\x3', '\x2', '\x2', 
		'\x2', 'H', '\x43', '\x3', '\x2', '\x2', '\x2', 'H', '\x44', '\x3', '\x2', 
		'\x2', '\x2', 'H', '\x45', '\x3', '\x2', '\x2', '\x2', 'H', '\x46', '\x3', 
		'\x2', '\x2', '\x2', 'H', 'G', '\x3', '\x2', '\x2', '\x2', 'I', '\v', 
		'\x3', '\x2', '\x2', '\x2', 'J', 'K', '\a', '\x14', '\x2', '\x2', 'K', 
		'L', '\a', '\b', '\x2', '\x2', 'L', '\r', '\x3', '\x2', '\x2', '\x2', 
		'M', 'N', '\a', '\t', '\x2', '\x2', 'N', 'O', '\a', '\x14', '\x2', '\x2', 
		'O', '_', '\a', '\n', '\x2', '\x2', 'P', 'Q', '\a', '\t', '\x2', '\x2', 
		'Q', 'R', '\a', '\x14', '\x2', '\x2', 'R', 'S', '\a', '\x4', '\x2', '\x2', 
		'S', 'T', '\a', '\x14', '\x2', '\x2', 'T', '_', '\a', '\n', '\x2', '\x2', 
		'U', 'V', '\a', '\t', '\x2', '\x2', 'V', 'W', '\a', '\x14', '\x2', '\x2', 
		'W', 'X', '\a', '\x4', '\x2', '\x2', 'X', 'Y', '\a', '\x14', '\x2', '\x2', 
		'Y', 'Z', '\a', '\x4', '\x2', '\x2', 'Z', '[', '\a', '\x14', '\x2', '\x2', 
		'[', '\\', '\a', '\x4', '\x2', '\x2', '\\', ']', '\a', '\x14', '\x2', 
		'\x2', ']', '_', '\a', '\n', '\x2', '\x2', '^', 'M', '\x3', '\x2', '\x2', 
		'\x2', '^', 'P', '\x3', '\x2', '\x2', '\x2', '^', 'U', '\x3', '\x2', '\x2', 
		'\x2', '_', '\xF', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', '\x13', 
		'\x2', '\x2', '\x61', '\x62', '\a', '\v', '\x2', '\x2', '\x62', 'g', '\x5', 
		'\x12', '\n', '\x2', '\x63', '\x64', '\a', '\x4', '\x2', '\x2', '\x64', 
		'\x66', '\x5', '\x12', '\n', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'i', '\x3', '\x2', '\x2', '\x2', 'g', '\x65', '\x3', '\x2', 
		'\x2', '\x2', 'g', 'h', '\x3', '\x2', '\x2', '\x2', 'h', 'j', '\x3', '\x2', 
		'\x2', '\x2', 'i', 'g', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', '\f', 
		'\x2', '\x2', 'k', '\x11', '\x3', '\x2', '\x2', '\x2', 'l', 'o', '\x5', 
		'\b', '\x5', '\x2', 'm', 'o', '\x5', '\x10', '\t', '\x2', 'n', 'l', '\x3', 
		'\x2', '\x2', '\x2', 'n', 'm', '\x3', '\x2', '\x2', '\x2', 'o', '\x13', 
		'\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', '\r', '\x2', '\x2', 'q', 'r', 
		'\x5', '\n', '\x6', '\x2', 'r', '\x15', '\x3', '\x2', '\x2', '\x2', 's', 
		't', '\a', '\xE', '\x2', '\x2', 't', 'u', '\x5', '\n', '\x6', '\x2', 'u', 
		'\x17', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\a', '\xF', '\x2', '\x2', 
		'w', 'x', '\x5', '\n', '\x6', '\x2', 'x', '\x19', '\x3', '\x2', '\x2', 
		'\x2', 'y', 'z', '\a', '\t', '\x2', '\x2', 'z', '\x81', '\x5', '\x6', 
		'\x4', '\x2', '{', '}', '\a', '\x4', '\x2', '\x2', '|', '{', '\x3', '\x2', 
		'\x2', '\x2', '|', '}', '\x3', '\x2', '\x2', '\x2', '}', '~', '\x3', '\x2', 
		'\x2', '\x2', '~', '\x80', '\x5', '\x6', '\x4', '\x2', '\x7F', '|', '\x3', 
		'\x2', '\x2', '\x2', '\x80', '\x83', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x84', '\x3', '\x2', '\x2', '\x2', '\x83', '\x81', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x85', '\a', '\n', '\x2', '\x2', '\x85', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\xF', '\"', '%', ')', '-', '\x30', 
		'\x33', '?', 'H', '^', 'g', 'n', '|', '\x81',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Shiba.Parser
