//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Shiba.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Shiba.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ShibaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, Script=2, Null=3, String=4, Boolean=5, Identifier=6, Number=7, 
		Arrow=8, Comma=9, Colon=10, Assign=11, LeftParen=12, RightParen=13, LeftBracket=14, 
		RightBracket=15, LeftBrace=16, RightBrace=17, Hws=18, Vws=19, DocComment=20, 
		BlockComment=21, LineComment=22, LineCommentExt=23;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "Script", "Null", "String", "Boolean", "Identifier", "Number", 
		"Arrow", "Comma", "Colon", "Assign", "LeftParen", "RightParen", "LeftBracket", 
		"RightBracket", "LeftBrace", "RightBrace", "INT", "EXP", "Hws", "Vws", 
		"DocComment", "BlockComment", "LineComment", "LineCommentExt"
	};


	public ShibaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ShibaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'$'", null, "'null'", null, null, null, null, "'->'", "','", "':'", 
		"'='", "'('", "')'", "'['", "']'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "Script", "Null", "String", "Boolean", "Identifier", "Number", 
		"Arrow", "Comma", "Colon", "Assign", "LeftParen", "RightParen", "LeftBracket", 
		"RightBracket", "LeftBrace", "RightBrace", "Hws", "Vws", "DocComment", 
		"BlockComment", "LineComment", "LineCommentExt"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Shiba.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ShibaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x19', '\xEE', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\a', '\x3', '<', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '?', 
		'\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', 
		'J', '\n', '\x5', '\f', '\x5', '\xE', '\x5', 'M', '\v', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x5', '\x6', 'Z', '\n', '\x6', '\x3', '\a', '\x6', '\a', ']', 
		'\n', '\a', '\r', '\a', '\xE', '\a', '^', '\x3', '\a', '\a', '\a', '\x62', 
		'\n', '\a', '\f', '\a', '\xE', '\a', '\x65', '\v', '\a', '\x3', '\b', 
		'\x5', '\b', 'h', '\n', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x6', 
		'\b', 'm', '\n', '\b', '\r', '\b', '\xE', '\b', 'n', '\x5', '\b', 'q', 
		'\n', '\b', '\x3', '\b', '\x5', '\b', 't', '\n', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\a', '\x13', '\x8E', '\n', '\x13', '\f', '\x13', 
		'\xE', '\x13', '\x91', '\v', '\x13', '\x5', '\x13', '\x93', '\n', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x5', '\x14', '\x97', '\n', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\a', 
		'\x17', '\xA8', '\n', '\x17', '\f', '\x17', '\xE', '\x17', '\xAB', '\v', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\xB0', 
		'\n', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\a', '\x18', '\xB8', '\n', '\x18', '\f', 
		'\x18', '\xE', '\x18', '\xBB', '\v', '\x18', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x5', '\x18', '\xC0', '\n', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\a', 
		'\x19', '\xC8', '\n', '\x19', '\f', '\x19', '\xE', '\x19', '\xCB', '\v', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\a', '\x1A', '\xD3', '\n', '\x1A', '\f', '\x1A', 
		'\xE', '\x1A', '\xD6', '\v', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\a', 
		'\x1A', '\xDA', '\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', '\xDD', '\v', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\a', 
		'\x1A', '\xE3', '\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', '\xE6', '\v', 
		'\x1A', '\a', '\x1A', '\xE8', '\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', 
		'\xEB', '\v', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x5', '=', '\xA9', 
		'\xB9', '\x2', '\x1B', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', 
		'\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', 
		'\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', 
		'\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x2', '\'', '\x2', ')', 
		'\x14', '+', '\x15', '-', '\x16', '/', '\x17', '\x31', '\x18', '\x33', 
		'\x19', '\x3', '\x2', '\r', '\x3', '\x2', '$', '$', '\x5', '\x2', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\a', '\x2', '\x30', '\x30', '\x32', 
		';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', '\x32', 
		';', '\x3', '\x2', '\x33', ';', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', 
		'\x2', '-', '-', '/', '/', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x4', 
		'\x2', '\f', '\f', '\xE', '\xF', '\x4', '\x2', '\f', '\f', '\xF', '\xF', 
		'\x3', '\x2', '\f', '\f', '\x2', '\x100', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x3', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '\x37', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\t', 'G', '\x3', '\x2', '\x2', '\x2', 
		'\v', 'Y', '\x3', '\x2', '\x2', '\x2', '\r', '\\', '\x3', '\x2', '\x2', 
		'\x2', '\xF', 'g', '\x3', '\x2', '\x2', '\x2', '\x11', 'u', '\x3', '\x2', 
		'\x2', '\x2', '\x13', 'x', '\x3', '\x2', '\x2', '\x2', '\x15', 'z', '\x3', 
		'\x2', '\x2', '\x2', '\x17', '|', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x82', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x84', '\x3', 
		'\x2', '\x2', '\x2', '!', '\x86', '\x3', '\x2', '\x2', '\x2', '#', '\x88', 
		'\x3', '\x2', '\x2', '\x2', '%', '\x92', '\x3', '\x2', '\x2', '\x2', '\'', 
		'\x94', '\x3', '\x2', '\x2', '\x2', ')', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '+', '\x9E', '\x3', '\x2', '\x2', '\x2', '-', '\xA2', '\x3', '\x2', 
		'\x2', '\x2', '/', '\xB3', '\x3', '\x2', '\x2', '\x2', '\x31', '\xC3', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\xCE', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x36', '\a', '&', '\x2', '\x2', '\x36', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\x38', '\a', '&', '\x2', '\x2', '\x38', '\x39', 
		'\a', '}', '\x2', '\x2', '\x39', '=', '\x3', '\x2', '\x2', '\x2', ':', 
		'<', '\v', '\x2', '\x2', '\x2', ';', ':', '\x3', '\x2', '\x2', '\x2', 
		'<', '?', '\x3', '\x2', '\x2', '\x2', '=', '>', '\x3', '\x2', '\x2', '\x2', 
		'=', ';', '\x3', '\x2', '\x2', '\x2', '>', '@', '\x3', '\x2', '\x2', '\x2', 
		'?', '=', '\x3', '\x2', '\x2', '\x2', '@', '\x41', '\a', '\x7F', '\x2', 
		'\x2', '\x41', '\x6', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\a', 
		'p', '\x2', '\x2', '\x43', '\x44', '\a', 'w', '\x2', '\x2', '\x44', '\x45', 
		'\a', 'n', '\x2', '\x2', '\x45', '\x46', '\a', 'n', '\x2', '\x2', '\x46', 
		'\b', '\x3', '\x2', '\x2', '\x2', 'G', 'K', '\a', '$', '\x2', '\x2', 'H', 
		'J', '\n', '\x2', '\x2', '\x2', 'I', 'H', '\x3', '\x2', '\x2', '\x2', 
		'J', 'M', '\x3', '\x2', '\x2', '\x2', 'K', 'I', '\x3', '\x2', '\x2', '\x2', 
		'K', 'L', '\x3', '\x2', '\x2', '\x2', 'L', 'N', '\x3', '\x2', '\x2', '\x2', 
		'M', 'K', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\a', '$', '\x2', '\x2', 
		'O', '\n', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\a', 'v', '\x2', '\x2', 
		'Q', 'R', '\a', 't', '\x2', '\x2', 'R', 'S', '\a', 'w', '\x2', '\x2', 
		'S', 'Z', '\a', 'g', '\x2', '\x2', 'T', 'U', '\a', 'h', '\x2', '\x2', 
		'U', 'V', '\a', '\x63', '\x2', '\x2', 'V', 'W', '\a', 'n', '\x2', '\x2', 
		'W', 'X', '\a', 'u', '\x2', '\x2', 'X', 'Z', '\a', 'g', '\x2', '\x2', 
		'Y', 'P', '\x3', '\x2', '\x2', '\x2', 'Y', 'T', '\x3', '\x2', '\x2', '\x2', 
		'Z', '\f', '\x3', '\x2', '\x2', '\x2', '[', ']', '\t', '\x3', '\x2', '\x2', 
		'\\', '[', '\x3', '\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', 
		'\x2', '^', '\\', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', 
		'\x2', '\x2', '_', '\x63', '\x3', '\x2', '\x2', '\x2', '`', '\x62', '\t', 
		'\x4', '\x2', '\x2', '\x61', '`', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '\x63', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', '\xE', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'h', '\a', '/', '\x2', '\x2', 'g', '\x66', '\x3', '\x2', '\x2', '\x2', 
		'g', 'h', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\x3', '\x2', '\x2', '\x2', 
		'i', 'p', '\x5', '%', '\x13', '\x2', 'j', 'l', '\a', '\x30', '\x2', '\x2', 
		'k', 'm', '\t', '\x5', '\x2', '\x2', 'l', 'k', '\x3', '\x2', '\x2', '\x2', 
		'm', 'n', '\x3', '\x2', '\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', 'q', '\x3', '\x2', '\x2', '\x2', 
		'p', 'j', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\x3', '\x2', '\x2', '\x2', 
		'q', 's', '\x3', '\x2', '\x2', '\x2', 'r', 't', '\x5', '\'', '\x14', '\x2', 
		's', 'r', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', '\x2', '\x2', '\x2', 
		't', '\x10', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', '/', '\x2', '\x2', 
		'v', 'w', '\a', '@', '\x2', '\x2', 'w', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'x', 'y', '\a', '.', '\x2', '\x2', 'y', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'z', '{', '\a', '<', '\x2', '\x2', '{', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'|', '}', '\a', '?', '\x2', '\x2', '}', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'~', '\x7F', '\a', '*', '\x2', '\x2', '\x7F', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '\x81', '\a', '+', '\x2', '\x2', '\x81', '\x1C', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x83', '\a', ']', '\x2', '\x2', '\x83', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', '_', '\x2', 
		'\x2', '\x85', ' ', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', 
		'}', '\x2', '\x2', '\x87', '\"', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', 
		'\a', '\x7F', '\x2', '\x2', '\x89', '$', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x93', '\a', '\x32', '\x2', '\x2', '\x8B', '\x8F', '\t', '\x6', '\x2', 
		'\x2', '\x8C', '\x8E', '\t', '\x5', '\x2', '\x2', '\x8D', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x91', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x93', '\x3', '\x2', '\x2', '\x2', '\x91', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x92', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x93', '&', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x96', '\t', '\a', '\x2', '\x2', '\x95', '\x97', '\t', 
		'\b', '\x2', '\x2', '\x96', '\x95', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x97', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x99', '\x5', '%', '\x13', '\x2', '\x99', '(', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x9B', '\t', '\t', '\x2', '\x2', '\x9B', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9D', '\b', '\x15', '\x2', 
		'\x2', '\x9D', '*', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\t', 
		'\n', '\x2', '\x2', '\x9F', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\xA1', '\b', '\x16', '\x2', '\x2', '\xA1', ',', '\x3', '\x2', '\x2', 
		'\x2', '\xA2', '\xA3', '\a', '\x31', '\x2', '\x2', '\xA3', '\xA4', '\a', 
		',', '\x2', '\x2', '\xA4', '\xA5', '\a', ',', '\x2', '\x2', '\xA5', '\xA9', 
		'\x3', '\x2', '\x2', '\x2', '\xA6', '\xA8', '\v', '\x2', '\x2', '\x2', 
		'\xA7', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xAB', '\x3', '\x2', 
		'\x2', '\x2', '\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xA7', 
		'\x3', '\x2', '\x2', '\x2', '\xAA', '\xAF', '\x3', '\x2', '\x2', '\x2', 
		'\xAB', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\a', ',', 
		'\x2', '\x2', '\xAD', '\xB0', '\a', '\x31', '\x2', '\x2', '\xAE', '\xB0', 
		'\a', '\x2', '\x2', '\x3', '\xAF', '\xAC', '\x3', '\x2', '\x2', '\x2', 
		'\xAF', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', 
		'\x2', '\x2', '\xB1', '\xB2', '\b', '\x17', '\x2', '\x2', '\xB2', '.', 
		'\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', '\a', '\x31', '\x2', '\x2', 
		'\xB4', '\xB5', '\a', ',', '\x2', '\x2', '\xB5', '\xB9', '\x3', '\x2', 
		'\x2', '\x2', '\xB6', '\xB8', '\v', '\x2', '\x2', '\x2', '\xB7', '\xB6', 
		'\x3', '\x2', '\x2', '\x2', '\xB8', '\xBB', '\x3', '\x2', '\x2', '\x2', 
		'\xB9', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xB7', '\x3', '\x2', 
		'\x2', '\x2', '\xBA', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB9', 
		'\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', '\a', ',', '\x2', '\x2', '\xBD', 
		'\xC0', '\a', '\x31', '\x2', '\x2', '\xBE', '\xC0', '\a', '\x2', '\x2', 
		'\x3', '\xBF', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\xC0', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC1', 
		'\xC2', '\b', '\x18', '\x2', '\x2', '\xC2', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xC4', '\a', '\x31', '\x2', '\x2', '\xC4', '\xC5', '\a', 
		'\x31', '\x2', '\x2', '\xC5', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC6', 
		'\xC8', '\n', '\v', '\x2', '\x2', '\xC7', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\xC8', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCA', 
		'\xCC', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xC9', '\x3', '\x2', '\x2', 
		'\x2', '\xCC', '\xCD', '\b', '\x19', '\x2', '\x2', '\xCD', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\xCE', '\xCF', '\a', '\x31', '\x2', '\x2', '\xCF', 
		'\xD0', '\a', '\x31', '\x2', '\x2', '\xD0', '\xD4', '\x3', '\x2', '\x2', 
		'\x2', '\xD1', '\xD3', '\n', '\f', '\x2', '\x2', '\xD2', '\xD1', '\x3', 
		'\x2', '\x2', '\x2', '\xD3', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD4', 
		'\xD2', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\xD5', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD4', '\x3', 
		'\x2', '\x2', '\x2', '\xD7', '\xDB', '\a', '\f', '\x2', '\x2', '\xD8', 
		'\xDA', '\x5', ')', '\x15', '\x2', '\xD9', '\xD8', '\x3', '\x2', '\x2', 
		'\x2', '\xDA', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xD9', '\x3', 
		'\x2', '\x2', '\x2', '\xDB', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDC', 
		'\xDE', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDB', '\x3', '\x2', '\x2', 
		'\x2', '\xDE', '\xDF', '\a', '\x31', '\x2', '\x2', '\xDF', '\xE0', '\a', 
		'\x31', '\x2', '\x2', '\xE0', '\xE4', '\x3', '\x2', '\x2', '\x2', '\xE1', 
		'\xE3', '\n', '\f', '\x2', '\x2', '\xE2', '\xE1', '\x3', '\x2', '\x2', 
		'\x2', '\xE3', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE2', '\x3', 
		'\x2', '\x2', '\x2', '\xE4', '\xE5', '\x3', '\x2', '\x2', '\x2', '\xE5', 
		'\xE8', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE4', '\x3', '\x2', '\x2', 
		'\x2', '\xE7', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xEB', '\x3', 
		'\x2', '\x2', '\x2', '\xE9', '\xE7', '\x3', '\x2', '\x2', '\x2', '\xE9', 
		'\xEA', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xEC', '\x3', '\x2', '\x2', 
		'\x2', '\xEB', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', '\b', 
		'\x1A', '\x2', '\x2', '\xED', '\x34', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x2', '=', 'K', 'Y', '\\', '^', '\x61', '\x63', 'g', 'n', 'p', 's', '\x8F', 
		'\x92', '\x96', '\xA9', '\xAF', '\xB9', '\xBF', '\xC9', '\xD4', '\xDB', 
		'\xE4', '\xE9', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Shiba.Parser
