//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Shiba.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Shiba.Parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IShibaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ShibaBaseListener : IShibaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.view"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterView([NotNull] ShibaParser.ViewContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.view"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitView([NotNull] ShibaParser.ViewContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] ShibaParser.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] ShibaParser.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] ShibaParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] ShibaParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMap([NotNull] ShibaParser.MapContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMap([NotNull] ShibaParser.MapContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.basicValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicValue([NotNull] ShibaParser.BasicValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.basicValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicValue([NotNull] ShibaParser.BasicValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] ShibaParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] ShibaParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.shibaExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShibaExtension([NotNull] ShibaParser.ShibaExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.shibaExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShibaExtension([NotNull] ShibaParser.ShibaExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] ShibaParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] ShibaParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ShibaParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] ShibaParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ShibaParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] ShibaParser.IdentifierContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Shiba.Parser
