name: Deploy CI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-and-deploy-UWP:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Show version
        working-directory: ./UWP
        run: echo %GITHUB_REF:~10%
      - name: Restore with nuget
        working-directory: ./UWP
        run: nuget restore ./Shiba.sln
      - name: Build with msbuild
        working-directory: ./UWP
        run: msbuild ./Shiba.sln /m /verbosity:minimal /p:Configuration=Release
      - name: Deploy to github packages
        working-directory: ./UWP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/ShibaJS/index.json" -UserName ShibaJS -Password GITHUB_TOKEN
          nuget pack ./Shiba.nuspec -Version %GITHUB_REF:~10%
          nuget push "Shiba.nupkg" -Source "GitHub"

  build-and-deploy-Android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Show version
        working-directory: ./Android
        run: echo ${GITHUB_REF:10}
      - name: Grant execute permission for gradlew
        working-directory: ./Android
        run: chmod +x ./gradlew
      - name: Build with Gradle
        working-directory: ./Android
        run: ./gradlew clean build
      - name: Deploy to github packages
        working-directory: ./Android
        run: ./gradlew publish -PversionName="${GITHUB_REF:10}" -Ptoken=GITHUB_TOKEN -Puser="ShibaJS"
