name: UWP CI

on: 
  push:
    paths:
      - 'UWP/**'

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Restore with dotnet
      working-directory: ./UWP
      run: dotnet restore ./Shiba.sln
    - name: Build with msbuild
      working-directory: ./UWP
      run: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe' ./Shiba.sln /m /verbosity:minimal /p:Configuration=Release
